name: Deploy To Servers

on:
  push:
    branches: [ "main" ]

jobs:
  deploy-103:
    runs-on: [self-hosted, API-Node1]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Deploy & Reload Application
        run: |
          sudo cp -r frontend/* /var/www/html/
          cp -f server.js package*.json ~/game-api/
          cd ~/game-api
          npm install
          pm2 reload all

  deploy-104:
    runs-on: [self-hosted, API-Node2]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Deploy & Reload Application
        run: |
          sudo cp -r frontend/* /var/www/html/
          cp -f server.js package*.json ~/game-api/
          cd ~/game-api
          npm install
          pm2 reload all



